[sources.kafka]
    type = "kafka"
    bootstrap_servers = ""
    group_id = ""
    key_field = "message_key"
    topics = ['']

    ## TLS
    #tls.enabled = ${ENABLE_TLS}
    #tls.ca_path = "${CA_PATH}"
    #tls.crt_path = "${CERT_PATH}"
    #tls.key_pass = "${KEY_PASS}"
    #tls.key_path = "${KEY_PATH}"
