[sources.kafka]
  type = "kafka"
  bootstrap_servers = "${BOOTSTRAP_SERVERS}"
  group_id = "${GROUP_ID}" 
  key_field = "${KEY_FIELD}" 
  topics = [${TOPICS}] 
  
# TLS
  tls.enabled = ${ENABLE_TLS}
  tls.ca_path = "${CA_PATH}" 
  tls.crt_path = "${CERT_PATH}" 
  tls.key_pass = "${KEY_PASS}" 
  tls.key_path = "${KEY_PATH}" 
