[sources.splunk_hec]
  type = "splunk_hec" 
  address = "${ADDRESS}" 
  token = ${TOKEN} 

  # TLS
  tls.enabled = ${TLS}
  tls.ca_path = "${CA_PATH}" 
  tls.crt_path = "${CERT_PATH}" 
  tls.key_pass = "${KEY_PASS}" 
  tls.key_path = "${KEY_PATH}" 
  tls.verify_certificate = ${VERIFY_CERT}