
[transforms.parser]
  inputs = ["${SOURCE_TYPE}"]
  type   = "json_parser"
  field  = "message"
  drop_invalid = true

[transforms.lua]
  inputs = ["parser"]
  type="lua"
  search_dirs = ['../scripts/lua', '../scripts/static']
  source= '''
require("date_utils")
require("general_utils")
require("numeric_utils")
require("variables")
require("string_field")
require("numeric_field")
require("time_field")
require("remove_input_fields")

handle_string(event)
handle_numeric(event)
handle_time(event)
remove_input_fields(event)
'''

[sinks.out]
  inputs = ["lua"] 
  type = "${OUTPUT}"
  encoding.codec = "ndjson"
  path = "${OUT_FILE}"