
[transforms.parser]
  inputs = ["${SOURCE_TYPE}"]
  type   = "json_parser"
  field  = "message"
  drop_invalid = true

[transforms.lua]
  inputs = ['parser']
  type="lua"
  search_dirs = ['../scripts/lua']
  source= '''
require("general_field")
require("string_field")
require("numeric_field")

handle_string(event)
handle_numeric(event)
handle_general(event)
'''

[sinks.out]
  inputs = ["lua"] 
  type = "${OUTPUT}"
  encoding.codec = "ndjson"
  path = "${OUT_FILE}"