data_dir = "${DATA_DIR}"

[sources.in]
  type = "${INPUT}"
  include = ["${IN_FILE}"]
  fingerprinting.fingerprint_bytes = 0
  fingerprinting.ignored_header_bytes = 0 
  fingerprinting.strategy = "checksum"
  start_at_beginning = true


[transforms.parser]
  type = "json_parser" 
  inputs = ["in"] 
  drop_field = true
  drop_invalid = true
  field = "message"

[transforms.lua]
  type="lua"
  search_dirs = ['../scripts/lua']
  inputs = ['parser']
  source= '''
require("general_field")
require("string_field")
require("replacer")
handle_string(event)
handle_replacement(event)
handle_general(event)
'''

[sinks.out]
  type = "${OUTPUT}"
  inputs = ["lua"] 
  encoding.codec = "ndjson"
  path = "${OUT_FILE}"