data_dir = "${DATA_DIR}"

[sources.in]
  type = "${INPUT}"
  fingerprinting.fingerprint_bytes = 0
  fingerprinting.ignored_header_bytes = 0 
  fingerprinting.strategy = "checksum"
  start_at_beginning = true

[transforms.parser]
  inputs = ["in"]
  type   = "json_parser"
  field  = "message"
  drop_invalid = true

[transforms.lua]
  inputs = ['parser']
  type="lua"
  search_dirs = ['../scripts/lua']
  source= '''
require("general_field")
require("string_field")
require("replacer")

handle_string(event)
handle_replacement(event)
handle_general(event)
'''

[sinks.out]
  inputs = ["lua"] 
  type = "${OUTPUT}"
  encoding.codec = "ndjson"
  path = "${OUT_FILE}"