data_dir = "/Users/dagmawi/Desktop/censys-ml/vector/data"

[sources.in]
    type = "${INPUT}"

[transforms.numeric]
    search_dirs = ["./scripts/lua"]
    inputs = ["in"]
    type = "lua"
    source = """
require("numeric_field")
handle_numeric(event)
    """

# [transforms.numeric]
#     type = "lua"
#     search_dirs = ["./scripts/lua"]
#     inputs = ["in"]
#     source = """
# require("numeric_field")
# require("string_field")
# require("time_field")

# print("Running...")

# add_numeric(event)
#     """

# [transforms.numeric]
#     type = "lua"
#     search_dirs = ["./scripts/lua"]
#     inputs = ["in"]
#     source = """
# require("numeric_field")
# require("string_field")
# require("time_field")

# print("Running...")

# add_numeric(event)
#     """

[sinks.out]
    inputs = ["numeric"]
    type = "${OUTPUT}"
    encoding = "ndjson"
    path = "/Users/dagmawi/Desktop/censys-ml/vector/data/vector-%Y-%m-%d.json"