data_dir = "${DATA_DIR}"

[sources.in]
    type = "${INPUT}"
    include = ["${IN_FILE}"]

[transforms.json]
  inputs = ["in"]
  type   = "json_parser"
  field  = "message"

[transforms.censys]
    search_dirs = ["./scripts/lua"]
    inputs = ["json"]
    type = "lua"
    source = """
require("numeric_field")
require("general_field")
require("string_field")

-- handle_numeric(event)
-- handle_string(event)
handle_general(event)
    """

# [transforms.numeric]
#     type = "lua"
#     search_dirs = ["./scripts/lua"]
#     inputs = ["in"]
#     source = """
# require("numeric_field")
# require("string_field")
# require("time_field")

# print("Running...")

# add_numeric(event)
#     """

# [transforms.numeric]
#     type = "lua"
#     search_dirs = ["./scripts/lua"]
#     inputs = ["in"]
#     source = """
# require("numeric_field")
# require("string_field")
# require("time_field")

# print("Running...")

# add_numeric(event)
#     """

[sinks.out]
    inputs = ["censys"]
    type = "${OUTPUT}"
    encoding = "ndjson"
    path = "/Users/dagmawi/Desktop/censys-ml/vector/output/vector-%Y-%m-%d.json"